query Tags($name: String!) {
  tags(filters: { name: { eq: $name } }) {
    data {
      id
      attributes {
        name
        episodes {
          data {
            id
            attributes {
              title
              slug
              createdAt
              updatedAt
              date
              description
              cover {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        podcasts(sort: "date:desc") {
          data {
            id
            attributes {
              title
              slug
              createdAt
              updatedAt
              date
              description
              cover {
                data {
                  attributes {
                    url
                  }
                }
              }
              episodes {
                data {
                  attributes {
                    title
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
