query AboutUS {
  aboutUs {
    data {
      attributes {
        title
        about
        cover {
          data {
            attributes {
              url
            }
          }
        }
        attachment {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
