query Global {
  global {
    data {
      attributes {
        site_name
        favicon {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
