query Homepage {
  homepage {
    seo {
      metaTitle
      metaDescription
      shareImage {
        name
        caption
        formats
        width
        height
        url
      }
    }
    hero {
      title
    }
  }
}
