query Homepage {
  homepage {
    seo {
      meta_title
      meta_description
      share_image {
        name
        caption
        formats
        width
        height
        url
      }
    }
    hero {
      title
    }
  }
}
