query Episodes($slug: String!) {
  episodes(filters: {slug: {eq: $slug } } ) {
    data {
      id
      attributes {
        title
        slug
        episode_number
        date
        description
        spreaker_id
        spreaker_limited
        tags {
          data {
            id
            attributes {
              name
            }
          }
        }
        cover {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        audio {
          data {
            attributes {
              url
            }
          }
        }
        podcast {
          data {
            attributes {
              title
              slug
            }
          }
        }
      }
    }
  }
}
