query Episodes  ($limit: Int!) {
  episodes (limit:$limit, sort: "date:desc") {
    id
    title
    slug
    episode_number
    date
    description
    spreaker_id
    spreaker_limited
    tags {
      name
    }
    cover {
      url
      width
      height
    }
    audio {
      url
    }
    schools {
      name
      short_name
      slug
    }
    podcast {
      title
      slug
      description
      tags {
        name
      }
      schools {
        name
        short_name
        slug
      }
    }
  }
}
