query Posts {
  posts(sort: "date:desc") {
    data {
      id
      attributes {
        title
        subtitle
        slug
        date
        article
        image {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        tags {
          data {
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
