query Posts($slug: String!) {
  posts (filters: {slug: {eq: $slug} } ){
    data {
      id
      attributes {
        slug
        title
        subtitle
        article
        image {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        tags {
          data {
            id
            attributes {
              name
              posts {
                data {
                  attributes {
                    title
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
