
@baseUrl = https://api.webe.radio/graphql
###
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Episodes($slug: String!) {
  episodes(filters: {slug: {eq: $slug } } ) {
    data {
      id
      attributes {
        title
        slug
        episode_number
        date
        description
        spreaker_id
        spreaker_limited
        tags {
          data {
            id
            attributes {
              name
            }
          }
        }
        cover {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        audio {
          data {
            attributes {
              url
            }
          }
        }
        podcast {
          data {
            attributes {
              title
              slug
            }
          }
        }
      }
    }
  }
}

{"slug":"fake-news-in-the-present"}


###
# @name pippo
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Episodes {
  episodes {
    id
    title
    slug
    episode_number
    date
    description
    spreaker_id
    tags {
      name
    }
    cover {
      url
      width
      height
    }
    audio {
      url
    }
    podcast {
      id
      title
      slug
    }
  }
}

###
@ep1 = {{pippo.response.body.$.data.episodes[0].slug}}
@ep2 = {{pippo.response.body.$.data.episodes[1].slug}}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Episodes($slug: String!) {
  episodes(where: {slug: $slug}) {
    id
    title
    slug
    episode_number
    date
    description
    spreaker_id
    tags {
      name
    }
    cover {
      url
      width
      height
    }
    audio {
      url
    }
    podcast {
      title
      slug
    }
  }
}

{
  "slug": "{{ep2}}"
}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Posts {
  posts(sort: "date:desc") {
    data {
      id
      attributes {
        title
        subtitle
        slug
        date
        article
        image {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        tags {
          data {
            id
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
